/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteRouteImport } from './routes/onboarding/route'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as OnboardingStoreSettingsRouteImport } from './routes/onboarding/store-settings'
import { Route as OnboardingFinishRouteImport } from './routes/onboarding/finish'
import { Route as OnboardingEmployeesRouteImport } from './routes/onboarding/employees'
import { Route as OnboardingDesignationsRouteImport } from './routes/onboarding/designations'
import { Route as OnboardingBranchRouteImport } from './routes/onboarding/branch'
import { Route as ProtectedTimesheetRouteImport } from './routes/_protected/timesheet'
import { Route as ProtectedEmployeesRouteImport } from './routes/_protected/employees'
import { Route as ProtectedDesignationsRouteImport } from './routes/_protected/designations'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedBranchesRouteImport } from './routes/_protected/branches'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as EStoreSlugRouteRouteImport } from './routes/e/$storeSlug/route'
import { Route as EStoreSlugIndexRouteImport } from './routes/e/$storeSlug/index'
import { Route as EStoreSlugEmployeeIdRouteImport } from './routes/e/$storeSlug/$employeeId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiResourcesStoreIdFieldOptionsRouteImport } from './routes/api/resources/$storeId.field-options'

const OnboardingRouteRoute = OnboardingRouteRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingStoreSettingsRoute = OnboardingStoreSettingsRouteImport.update({
  id: '/store-settings',
  path: '/store-settings',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingFinishRoute = OnboardingFinishRouteImport.update({
  id: '/finish',
  path: '/finish',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingEmployeesRoute = OnboardingEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingDesignationsRoute = OnboardingDesignationsRouteImport.update({
  id: '/designations',
  path: '/designations',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingBranchRoute = OnboardingBranchRouteImport.update({
  id: '/branch',
  path: '/branch',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const ProtectedTimesheetRoute = ProtectedTimesheetRouteImport.update({
  id: '/timesheet',
  path: '/timesheet',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedEmployeesRoute = ProtectedEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedDesignationsRoute = ProtectedDesignationsRouteImport.update({
  id: '/designations',
  path: '/designations',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedBranchesRoute = ProtectedBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authRouteRoute,
} as any)
const EStoreSlugRouteRoute = EStoreSlugRouteRouteImport.update({
  id: '/e/$storeSlug',
  path: '/e/$storeSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const EStoreSlugIndexRoute = EStoreSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EStoreSlugRouteRoute,
} as any)
const EStoreSlugEmployeeIdRoute = EStoreSlugEmployeeIdRouteImport.update({
  id: '/$employeeId',
  path: '/$employeeId',
  getParentRoute: () => EStoreSlugRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResourcesStoreIdFieldOptionsRoute =
  ApiResourcesStoreIdFieldOptionsRouteImport.update({
    id: '/api/resources/$storeId/field-options',
    path: '/api/resources/$storeId/field-options',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/e/$storeSlug': typeof EStoreSlugRouteRouteWithChildren
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/branches': typeof ProtectedBranchesRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/designations': typeof ProtectedDesignationsRoute
  '/employees': typeof ProtectedEmployeesRoute
  '/timesheet': typeof ProtectedTimesheetRoute
  '/onboarding/branch': typeof OnboardingBranchRoute
  '/onboarding/designations': typeof OnboardingDesignationsRoute
  '/onboarding/employees': typeof OnboardingEmployeesRoute
  '/onboarding/finish': typeof OnboardingFinishRoute
  '/onboarding/store-settings': typeof OnboardingStoreSettingsRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/e/$storeSlug/$employeeId': typeof EStoreSlugEmployeeIdRoute
  '/e/$storeSlug/': typeof EStoreSlugIndexRoute
  '/api/resources/$storeId/field-options': typeof ApiResourcesStoreIdFieldOptionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/branches': typeof ProtectedBranchesRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/designations': typeof ProtectedDesignationsRoute
  '/employees': typeof ProtectedEmployeesRoute
  '/timesheet': typeof ProtectedTimesheetRoute
  '/onboarding/branch': typeof OnboardingBranchRoute
  '/onboarding/designations': typeof OnboardingDesignationsRoute
  '/onboarding/employees': typeof OnboardingEmployeesRoute
  '/onboarding/finish': typeof OnboardingFinishRoute
  '/onboarding/store-settings': typeof OnboardingStoreSettingsRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/e/$storeSlug/$employeeId': typeof EStoreSlugEmployeeIdRoute
  '/e/$storeSlug': typeof EStoreSlugIndexRoute
  '/api/resources/$storeId/field-options': typeof ApiResourcesStoreIdFieldOptionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/e/$storeSlug': typeof EStoreSlugRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/_protected/branches': typeof ProtectedBranchesRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/designations': typeof ProtectedDesignationsRoute
  '/_protected/employees': typeof ProtectedEmployeesRoute
  '/_protected/timesheet': typeof ProtectedTimesheetRoute
  '/onboarding/branch': typeof OnboardingBranchRoute
  '/onboarding/designations': typeof OnboardingDesignationsRoute
  '/onboarding/employees': typeof OnboardingEmployeesRoute
  '/onboarding/finish': typeof OnboardingFinishRoute
  '/onboarding/store-settings': typeof OnboardingStoreSettingsRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/e/$storeSlug/$employeeId': typeof EStoreSlugEmployeeIdRoute
  '/e/$storeSlug/': typeof EStoreSlugIndexRoute
  '/api/resources/$storeId/field-options': typeof ApiResourcesStoreIdFieldOptionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/e/$storeSlug'
    | '/sign-in'
    | '/sign-up'
    | '/branches'
    | '/dashboard'
    | '/designations'
    | '/employees'
    | '/timesheet'
    | '/onboarding/branch'
    | '/onboarding/designations'
    | '/onboarding/employees'
    | '/onboarding/finish'
    | '/onboarding/store-settings'
    | '/onboarding/'
    | '/api/auth/$'
    | '/e/$storeSlug/$employeeId'
    | '/e/$storeSlug/'
    | '/api/resources/$storeId/field-options'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/branches'
    | '/dashboard'
    | '/designations'
    | '/employees'
    | '/timesheet'
    | '/onboarding/branch'
    | '/onboarding/designations'
    | '/onboarding/employees'
    | '/onboarding/finish'
    | '/onboarding/store-settings'
    | '/onboarding'
    | '/api/auth/$'
    | '/e/$storeSlug/$employeeId'
    | '/e/$storeSlug'
    | '/api/resources/$storeId/field-options'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/_protected'
    | '/onboarding'
    | '/e/$storeSlug'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/_protected/branches'
    | '/_protected/dashboard'
    | '/_protected/designations'
    | '/_protected/employees'
    | '/_protected/timesheet'
    | '/onboarding/branch'
    | '/onboarding/designations'
    | '/onboarding/employees'
    | '/onboarding/finish'
    | '/onboarding/store-settings'
    | '/onboarding/'
    | '/api/auth/$'
    | '/e/$storeSlug/$employeeId'
    | '/e/$storeSlug/'
    | '/api/resources/$storeId/field-options'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  OnboardingRouteRoute: typeof OnboardingRouteRouteWithChildren
  EStoreSlugRouteRoute: typeof EStoreSlugRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiResourcesStoreIdFieldOptionsRoute: typeof ApiResourcesStoreIdFieldOptionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/store-settings': {
      id: '/onboarding/store-settings'
      path: '/store-settings'
      fullPath: '/onboarding/store-settings'
      preLoaderRoute: typeof OnboardingStoreSettingsRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/finish': {
      id: '/onboarding/finish'
      path: '/finish'
      fullPath: '/onboarding/finish'
      preLoaderRoute: typeof OnboardingFinishRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/employees': {
      id: '/onboarding/employees'
      path: '/employees'
      fullPath: '/onboarding/employees'
      preLoaderRoute: typeof OnboardingEmployeesRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/designations': {
      id: '/onboarding/designations'
      path: '/designations'
      fullPath: '/onboarding/designations'
      preLoaderRoute: typeof OnboardingDesignationsRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/branch': {
      id: '/onboarding/branch'
      path: '/branch'
      fullPath: '/onboarding/branch'
      preLoaderRoute: typeof OnboardingBranchRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/_protected/timesheet': {
      id: '/_protected/timesheet'
      path: '/timesheet'
      fullPath: '/timesheet'
      preLoaderRoute: typeof ProtectedTimesheetRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/employees': {
      id: '/_protected/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof ProtectedEmployeesRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/designations': {
      id: '/_protected/designations'
      path: '/designations'
      fullPath: '/designations'
      preLoaderRoute: typeof ProtectedDesignationsRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/branches': {
      id: '/_protected/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof ProtectedBranchesRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/e/$storeSlug': {
      id: '/e/$storeSlug'
      path: '/e/$storeSlug'
      fullPath: '/e/$storeSlug'
      preLoaderRoute: typeof EStoreSlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$storeSlug/': {
      id: '/e/$storeSlug/'
      path: '/'
      fullPath: '/e/$storeSlug/'
      preLoaderRoute: typeof EStoreSlugIndexRouteImport
      parentRoute: typeof EStoreSlugRouteRoute
    }
    '/e/$storeSlug/$employeeId': {
      id: '/e/$storeSlug/$employeeId'
      path: '/$employeeId'
      fullPath: '/e/$storeSlug/$employeeId'
      preLoaderRoute: typeof EStoreSlugEmployeeIdRouteImport
      parentRoute: typeof EStoreSlugRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/resources/$storeId/field-options': {
      id: '/api/resources/$storeId/field-options'
      path: '/api/resources/$storeId/field-options'
      fullPath: '/api/resources/$storeId/field-options'
      preLoaderRoute: typeof ApiResourcesStoreIdFieldOptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface authRouteRouteChildren {
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface ProtectedRouteRouteChildren {
  ProtectedBranchesRoute: typeof ProtectedBranchesRoute
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedDesignationsRoute: typeof ProtectedDesignationsRoute
  ProtectedEmployeesRoute: typeof ProtectedEmployeesRoute
  ProtectedTimesheetRoute: typeof ProtectedTimesheetRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedBranchesRoute: ProtectedBranchesRoute,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedDesignationsRoute: ProtectedDesignationsRoute,
  ProtectedEmployeesRoute: ProtectedEmployeesRoute,
  ProtectedTimesheetRoute: ProtectedTimesheetRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

interface OnboardingRouteRouteChildren {
  OnboardingBranchRoute: typeof OnboardingBranchRoute
  OnboardingDesignationsRoute: typeof OnboardingDesignationsRoute
  OnboardingEmployeesRoute: typeof OnboardingEmployeesRoute
  OnboardingFinishRoute: typeof OnboardingFinishRoute
  OnboardingStoreSettingsRoute: typeof OnboardingStoreSettingsRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteRouteChildren: OnboardingRouteRouteChildren = {
  OnboardingBranchRoute: OnboardingBranchRoute,
  OnboardingDesignationsRoute: OnboardingDesignationsRoute,
  OnboardingEmployeesRoute: OnboardingEmployeesRoute,
  OnboardingFinishRoute: OnboardingFinishRoute,
  OnboardingStoreSettingsRoute: OnboardingStoreSettingsRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteRouteWithChildren = OnboardingRouteRoute._addFileChildren(
  OnboardingRouteRouteChildren,
)

interface EStoreSlugRouteRouteChildren {
  EStoreSlugEmployeeIdRoute: typeof EStoreSlugEmployeeIdRoute
  EStoreSlugIndexRoute: typeof EStoreSlugIndexRoute
}

const EStoreSlugRouteRouteChildren: EStoreSlugRouteRouteChildren = {
  EStoreSlugEmployeeIdRoute: EStoreSlugEmployeeIdRoute,
  EStoreSlugIndexRoute: EStoreSlugIndexRoute,
}

const EStoreSlugRouteRouteWithChildren = EStoreSlugRouteRoute._addFileChildren(
  EStoreSlugRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  OnboardingRouteRoute: OnboardingRouteRouteWithChildren,
  EStoreSlugRouteRoute: EStoreSlugRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiResourcesStoreIdFieldOptionsRoute: ApiResourcesStoreIdFieldOptionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
